on: [ push, pull_request ]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Clippy
        run: cargo clippy

  build:
    name: Build
    runs-on: ubuntu-latest
#    needs: [ check ]
    strategy:
      #fail-fast: true
      matrix:
        target:
          - value: "x86_64-unknown-linux-gnu"
            deps: ""
          - value: "x86_64-unknown-linux-musl"
            deps: "musl-tools"
          - value: "armv7-unknown-linux-gnueabihf"
            deps: "gcc-arm-linux-gnueabihf"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target.value }}
          override: true
      - name: "Install build dependencies"
        if: "${{ matrix.target.deps != '' }}"
        run: "sudo apt-get --assume-yes install ${{ matrix.target.deps }}"
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target.value }}
      - run: cargo install cargo-deb
      - run: cargo deb --target=${{ matrix.target.value }}

