name: Deb Static Build

on: [push]

jobs:
  debbuild:
    runs-on: ubuntu-latest
    name: Amd64Deb
    steps:
      - uses: actions/checkout@v2
      - name: BuildDeb
        id: debbuild
        uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
        with:
          cmd: cargo deb
      - name: Upload Deb Artifact
        uses: actions/upload-artifact@v2
        with:
          name: amd64deb
          path: ./target/x86_64-unknown-linux-amd64/debian/*
  raspbianbuild:
    runs-on: ubuntu-latest
    name: Armv7Deb
    steps:
      - uses: actions/checkout@v2
      - name: BuildDeb
        id: debbuild
        uses: ebbflow-io/cargo-deb-armv7-debian@1.0
        with:
          cmd: cargo deb
      - name: Upload Deb Artifact
        uses: actions/upload-artifact@v2
        with:
          name: armv7deb
          path: ./target/armv7-unknown-linux-musleabihf/debian/*
